import type React from "react";

export function getStyles(isMobile: boolean): Record<string, React.CSSProperties> {
    const card = cardStyle(isMobile);

    return {
        loginPage: {
            minHeight: "100vh",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            background:
                "radial-gradient(circle at top left, rgba(236,72,153,0.22), transparent 32%), radial-gradient(circle at bottom right, rgba(249,115,22,0.18), transparent 32%), #070711",
            color: "white",
            fontFamily:
                "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
            padding: 18,
            boxSizing: "border-box",
        },
        loginCard: {
            width: "100%",
            maxWidth: 440,
            background: "rgba(255,255,255,0.055)",
            border: "1px solid rgba(255,255,255,0.10)",
            borderRadius: 28,
            padding: isMobile ? 22 : 30,
            boxShadow: "0 30px 90px rgba(0,0,0,0.42)",
            boxSizing: "border-box",
        },
        loginTitle: {
            margin: "8px 0 0",
            fontSize: 42,
            lineHeight: 1,
            fontWeight: 950,
            letterSpacing: -1.5,
        },
        loginHint: {
            marginTop: 16,
            textAlign: "center",
            color: "#94a3b8",
            fontSize: 13,
        },
        page: {
            minHeight: "100vh",
            width: "100%",
            overflowX: "hidden",
            background:
                "radial-gradient(circle at top left, rgba(236,72,153,0.18), transparent 30%), #070711",
            color: "white",
            fontFamily:
                "Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, sans-serif",
        },
        container: {
            width: "100%",
            maxWidth: 1280,
            margin: "0 auto",
            padding: isMobile ? "18px 14px 32px" : "32px 24px",
            boxSizing: "border-box",
        },
        header: {
            display: "flex",
            flexDirection: isMobile ? "column" : "row",
            justifyContent: "space-between",
            gap: isMobile ? 16 : 24,
            alignItems: isMobile ? "stretch" : "flex-end",
            marginBottom: isMobile ? 18 : 28,
        },
        headerActions: {
            display: "flex",
            alignItems: "center",
            gap: 12,
            flexWrap: "wrap",
            justifyContent: isMobile ? "space-between" : "flex-end",
        },
        tabButton: {
            border: "1px solid rgba(255,255,255,0.12)",
            borderRadius: 16,
            padding: "13px 18px",
            color: "white",
            fontWeight: 800,
            cursor: "pointer",
        },
        badge: {
            display: "inline-block",
            padding: "6px 14px",
            borderRadius: 999,
            background: "rgba(236,72,153,0.12)",
            border: "1px solid rgba(236,72,153,0.35)",
            color: "#f9a8d4",
            fontSize: 13,
            marginBottom: 12,
        },
        title: {
            margin: 0,
            fontSize: isMobile ? 36 : 56,
            lineHeight: 1,
            fontWeight: 950,
            letterSpacing: isMobile ? -1 : -2,
        },
        subtitle: {
            marginTop: 12,
            color: "#94a3b8",
            fontSize: isMobile ? 15 : 18,
            lineHeight: 1.5,
        },
        button: {
            border: 0,
            borderRadius: 18,
            padding: "15px 22px",
            background: "linear-gradient(90deg,#db2777,#f97316)",
            color: "white",
            fontWeight: 900,
            fontSize: 16,
            boxShadow: "0 20px 50px rgba(219,39,119,0.25)",
        },
        logoutButton: {
            border: "1px solid rgba(255,255,255,0.12)",
            borderRadius: 16,
            padding: "13px 18px",
            background: "rgba(255,255,255,0.08)",
            color: "white",
            fontWeight: 800,
            cursor: "pointer",
        },
        grid: {
            display: "grid",
            gridTemplateColumns: isMobile ? "1fr" : "420px 1fr",
            gap: isMobile ? 18 : 24,
            alignItems: "start",
            width: "100%",
        },
        adminGrid: {
            display: "grid",
            gridTemplateColumns: isMobile ? "1fr" : "420px 1fr",
            gap: 24,
            alignItems: "start",
        },
        card,
        main: {
            display: "grid",
            gridTemplateColumns: isMobile ? "1fr" : "1fr 340px",
            gap: isMobile ? 18 : 24,
            minWidth: 0,
        },
        videoCard: card,
        panel: card,
        label: {
            display: "block",
            color: "#94a3b8",
            fontSize: 13,
            marginBottom: 8,
            marginTop: 14,
        },
        input: {
            width: "100%",
            height: 48,
            borderRadius: 16,
            border: "1px solid rgba(255,255,255,0.1)",
            background: "#020617",
            color: "white",
            padding: "0 14px",
            outline: "none",
            fontSize: 16,
            boxSizing: "border-box",
        },
        uploadBox: {
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "center",
            minHeight: isMobile ? 118 : 130,
            borderRadius: 22,
            border: "2px dashed rgba(255,255,255,0.12)",
            background: "#020617",
            cursor: "pointer",
        },
        previewHeader: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            color: "#94a3b8",
            fontSize: 13,
            marginBottom: 10,
            gap: 10,
            flexWrap: "wrap",
        },
        previewActions: {
            display: "flex",
            alignItems: "center",
            gap: 8,
            flexWrap: "wrap",
        },
        count: {
            background: "rgba(236,72,153,0.12)",
            color: "#f9a8d4",
            borderRadius: 999,
            padding: "2px 10px",
        },
        clearButton: {
            border: 0,
            borderRadius: 999,
            padding: "4px 10px",
            background: "rgba(239,68,68,0.15)",
            color: "#fecaca",
            fontSize: 12,
            fontWeight: 700,
            cursor: "pointer",
        },
        previewGrid: {
            display: "grid",
            gridTemplateColumns: isMobile ? "repeat(4, minmax(0, 1fr))" : "repeat(4, 1fr)",
            gap: 8,
        },
        thumb: {
            aspectRatio: "1/1",
            borderRadius: 14,
            overflow: "hidden",
            border: "1px solid rgba(255,255,255,0.1)",
            background: "black",
            position: "relative",
            minWidth: 0,
        },
        thumbImg: {
            width: "100%",
            height: "100%",
            objectFit: "cover",
            display: "block",
        },
        index: {
            position: "absolute",
            top: 5,
            left: 5,
            background: "rgba(0,0,0,0.7)",
            borderRadius: 999,
            padding: "2px 7px",
            fontSize: 11,
        },
        removeButton: {
            position: "absolute",
            top: 5,
            right: 5,
            width: 24,
            height: 24,
            borderRadius: 999,
            border: "1px solid rgba(255,255,255,0.2)",
            background: "rgba(0,0,0,0.75)",
            color: "white",
            fontSize: 18,
            lineHeight: "20px",
            cursor: "pointer",
        },
        jobBox: {
            marginTop: 18,
            background: "#020617",
            borderRadius: 18,
            padding: 14,
            border: "1px solid rgba(255,255,255,0.08)",
        },
        small: {
            color: "#64748b",
            fontSize: 12,
            textAlign: "center",
        },
        jobId: {
            fontSize: 13,
            wordBreak: "break-all",
            marginBottom: 10,
            textAlign: "center",
        },
        progressHeader: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            color: "#cbd5e1",
            fontSize: 13,
            marginTop: 14,
            marginBottom: 8,
            gap: 12,
        },
        progressBar: {
            width: "100%",
            height: 10,
            borderRadius: 999,
            background: "#1e293b",
            overflow: "hidden",
            marginBottom: 14,
        },
        progressFill: {
            height: "100%",
            borderRadius: 999,
            background: "linear-gradient(90deg,#22c55e,#06b6d4)",
            transition: "width 0.35s ease",
        },
        status: {
            fontWeight: 900,
            fontSize: 22,
            textAlign: "center",
        },
        error: {
            marginTop: 10,
            color: "#fecaca",
            background: "rgba(239,68,68,0.12)",
            border: "1px solid rgba(239,68,68,0.25)",
            padding: 10,
            borderRadius: 12,
            fontSize: 13,
        },
        adminMessage: {
            marginTop: 14,
            color: "#bfdbfe",
            background: "rgba(59,130,246,0.12)",
            border: "1px solid rgba(59,130,246,0.22)",
            padding: 10,
            borderRadius: 12,
            fontSize: 13,
        },
        sectionHeader: {
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            marginBottom: 16,
            gap: 12,
        },
        sectionTitle: {
            margin: 0,
            fontSize: isMobile ? 22 : 24,
        },
        link: {
            color: "white",
            textDecoration: "none",
            background: "rgba(255,255,255,0.1)",
            padding: "8px 14px",
            borderRadius: 999,
            fontSize: 13,
            flexShrink: 0,
        },
        video: {
            width: "100%",
            maxHeight: isMobile ? 560 : 760,
            borderRadius: 22,
            background: "black",
            display: "block",
        },
        emptyVideo: {
            height: isMobile ? 180 : 260,
            borderRadius: 22,
            border: "1px dashed rgba(255,255,255,0.12)",
            background: "#020617",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            color: "#64748b",
            textAlign: "center",
            padding: 20,
            boxSizing: "border-box",
        },
        sideGrid: {
            display: "grid",
            gap: isMobile ? 18 : 24,
            minWidth: 0,
        },
        panelTitle: {
            margin: "0 0 12px",
            fontSize: 18,
            textAlign: "center",
        },
        script: {
            background: "#020617",
            borderRadius: 16,
            padding: 14,
            color: "#cbd5e1",
            minHeight: isMobile ? 120 : 180,
            maxHeight: isMobile ? 220 : 260,
            overflow: "auto",
            whiteSpace: "pre-wrap",
            lineHeight: 1.6,
            boxSizing: "border-box",
        },
        logBox: {
            background: "#000",
            borderRadius: 16,
            padding: 14,
            color: "#4ade80",
            height: isMobile ? 180 : 260,
            overflow: "auto",
            fontFamily: "monospace",
            fontSize: 12,
            lineHeight: 1.6,
            boxSizing: "border-box",
        },
        userList: {
            display: "grid",
            gap: 12,
        },
        userItem: {
            display: "flex",
            justifyContent: "space-between",
            gap: 14,
            padding: 14,
            borderRadius: 16,
            background: "#020617",
            border: "1px solid rgba(255,255,255,0.08)",
        },
        userName: {
            fontWeight: 900,
            fontSize: 16,
        },
        userSub: {
            color: "#94a3b8",
            fontSize: 13,
            marginTop: 4,
        },
        userRoles: {
            color: "#f9a8d4",
            fontWeight: 900,
            fontSize: 13,
            whiteSpace: "nowrap",
        },
    };
}

export function cardStyle(isMobile: boolean): React.CSSProperties {
    return {
        background: "rgba(255,255,255,0.045)",
        border: "1px solid rgba(255,255,255,0.09)",
        borderRadius: isMobile ? 22 : 28,
        padding: isMobile ? 16 : 22,
        boxShadow: "0 30px 80px rgba(0,0,0,0.35)",
        width: "100%",
        maxWidth: "100%",
        minWidth: 0,
        boxSizing: "border-box",
    };
}